<!DOCTYPE html>
<html>
<title>Exceptional Handling</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

<body>

<div class="w3-container w3-orange">
  <h1>C++:Exceptional Handling</h1> 
  <p>The Contents are here...</p> 
</div>

<div class="w3-row-padding">

<div class="w3-third">
  <h2>Description</h2>
  <p>An exception is a problem that arises during the execution of a program. A C++ exception is a response to an exceptional circumstance that arises while a program is running, such as an attempt to divide by zero.<br><br>

Exceptions provide a way to transfer control from one part of a program to another. C++ exception handling is built upon three keywords: try, catch, and throw.<br><br>

throw: A program throws an exception when a problem shows up. This is done using a throw keyword.<br><br>

catch: A program catches an exception with an exception handler at the place in a program where you want to handle the problem. The catch keyword indicates the catching of an exception.<br><br>

try: A try block identifies a block of code for which particular exceptions will be activated. It's followed by one or more catch blocks.</p>
</div>
  

<div class="w3-third">
  <h2>Example</h2>
  <p>#include <iostream><br>
using namespace std;<br>

double division(int a, int b)<br>
{
   if( b == 0 )<br>
   {
      throw "Division by zero condition!";<br>
   }
   return (a/b);<br>
}

int main ()<br>
{<br>
   int x = 50;<br>
   int y = 0;<br>
   double z = 0;<br>
 
   try {<br>
     z = division(x, y);<br>
     cout << z << endl;<br>
   }catch (const char* msg) {<br>
     cerr << msg << endl;<br>
   }<br>

   return 0;<br>
}</p> 
</div>

<div class="w3-third">
  <h2>Reference</h2>
  <p>http://www.tutorialspoint.com/cplusplus/cpp_exceptions_handling.htm</p>
  
</div>

</div>
</body>
</html>
